<?php

// INSERT DATA_A24
"INSERT INTO DATA_A24 (NOMOR, NAMA, NIP, PELAKSANAAN_PENDIDIKAN,
KATEGORI_PEMBIMBING, NAMA_MAHASISWA, JENIS_TUGASAKHIR, TAHUN_AJARAN,
SEMESTER, TEMPAT, TANGGAL, KETERANGAN) VALUES (DATA_A24_SEQ.NEXTVAL,
'Idris Winarno', '198203082008121001', 
'Program D4 Lanjut Jenjang Semester Gasal Tahun Akademik 2012/2013', 
'PU', 'Hariken Pamungkas', 'Skripsi', '2012/2013', 'Gasal', 'PENS', '06-MAR-2013', 
'0564/PL14/AK/2013');";

// INSERT DATA_A25
"INSERT INTO DATA_A25 (NOMOR, NAMA, NIP, PELAKSANAAN_PENDIDIKAN,
KATEGORI_PENGUJI, NAMA_MAHASISWA, TAHUN_AJARAN,
SEMESTER, TEMPAT, TANGGAL, KETERANGAN) VALUES (DATA_A25_SEQ.NEXTVAL,
'Idris Winarno', '198203082008121001', 
'Program D4 Lanjut Jenjang Semester Gasal Tahun Akademik 2012/2013', 
'AP', 'Andris Dipura', '2012/2013', 'Gasal', 'PENS', '06-MAR-2013', 
'0565/PL14/AK/2013');";

"CREATE TABLE NAMA_TABLE (
NOMOR NUMBER(11) PRIMARY KEY,
NAMA VARCHAR(255)
);";

"CREATE TABLE PENGHITUNG (
    NOMOR NUMBER(11) PRIMARY KEY,
    NOMOR_BIDANG NUMBER(11) REFERENCES BIDANG(NOMOR),
    PROGRAM VARCHAR(255),
    JABATAN_FUNGSIONAL VARCHAR(255),
    ANGKA_KREDIT FLOAT(11),
    BATAS_SKS_PERTAMA NUMBER(11),
    BATAS_SKS_BERIKUTNYA NUMBER(11),
    ANGKA_KREDIT_PERTAMA FLOAT(11),
    ANGKA_KREDIT_BERIKUTNYA FLOAT(11),
    KATEGORI_PEMBIMBING VARCHAR(255),
    JENIS_TUGAS_AKHIR VARCHAR(255),
    KATEGORI_PENGUJI VARCHAR(255),
    JENIS_PRODUK VARCHAR(255),
    JABATAN_PIMPINAN VARCHAR(255),
    KATEGORI_PEMBIMBING_DOSEN VARCHAR(255),
    KATEGORI_KEGIATAN VARCHAR(255),
    DURASI_PENGEMBANGAN_DIRI VARCHAR(255),
    KEDUDUKAN VARCHAR(255),
    JENIS_PANITIA VARCHAR(255),
    KEDUDUKAN_PADA_LEMBAGA VARCHAR(255),
    TINGKATAN_ORGANISASI_PROFESI VARCHAR(255),
    KEDUDUKAN_ORGANISASI_PROFESI VARCHAR(255),
    KEDUDUKAN_PADA_DELEGASI VARCHAR(255),
    TINGKATAN_PERTEMUAN_ILMIAH VARCHAR(255),
    KEDUDUKAN_PERTEMUAN_ILMIAH VARCHAR(255),
    KATEGORI_PENGHARGAAN VARCHAR(255),
    TINGKATAN_BUKU_PELAJARAN VARCHAR(255),
    TINGKATAN_PRESTASI_OLAHRAGA VARCHAR(255),
    BATAS_MAKSIMAL NUMBER(11)
);";

"CREATE SEQUENCE PENGHITUNG_SEQ
MINVALUE 0
MAXVALUE 99999
START WITH 0
INCREMENT BY 1
NOCACHE;"

?>